# Generated by Django 3.0.5 on 2020-04-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer_record',
            name='id',
        ),
        migrations.AddField(
            model_name='farmer_record',
            name='farmer_id',
            field=models.IntegerField(default='1', primary_key=True, serialize=False),
        ),
    ]
