# Generated by Django 3.0.5 on 2020-04-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_website', '0002_auto_20200416_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer_record',
            name='farmer_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
