# Generated by Django 3.0.5 on 2020-04-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_website', '0003_auto_20200416_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='animal_reord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_no', models.IntegerField()),
                ('animal_dob', models.DateField()),
                ('body_weight', models.IntegerField()),
                ('animal_type', models.CharField(max_length=20)),
                ('breed_type', models.CharField(max_length=20)),
                ('current_lactation', models.IntegerField()),
                ('last_calving_date', models.DateField()),
                ('cattle_inseminated', models.CharField(max_length=10)),
                ('inseminated_type', models.CharField(max_length=30)),
                ('inseminated_date', models.DateField()),
                ('animal_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
