# Generated by Django 3.0.5 on 2020-04-16 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_website', '0005_auto_20200416_2034'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='animal_reord',
            new_name='animal_record',
        ),
    ]
