# Generated by Django 3.0.5 on 2020-04-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_website', '0007_auto_20200417_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal_record',
            name='animal_image',
            field=models.ImageField(upload_to='animal_images/'),
        ),
    ]
