# Generated by Django 3.0.5 on 2020-04-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_website', '0011_auto_20200420_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal_record',
            name='animal_image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
