# Generated by Django 3.0.5 on 2020-04-20 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_website', '0012_auto_20200420_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal_record',
            name='animal_image',
        ),
    ]
