# Generated by Django 3.0.5 on 2020-04-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_website', '0013_remove_animal_record_animal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal_record',
            name='animal_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
