# Generated by Django 3.0.5 on 2020-04-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_website', '0014_animal_record_animal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal_record',
            name='tag_no',
            field=models.CharField(max_length=15),
        ),
    ]
