# Generated by Django 3.0.5 on 2020-04-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_website', '0015_auto_20200421_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='vaccination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_type', models.DateField(default='----')),
                ('date', models.DateField(default='----')),
                ('is_done', models.BooleanField(null=True)),
            ],
        ),
    ]
