# Generated by Django 3.0.5 on 2020-04-22 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_website', '0016_vaccination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccination',
            old_name='date',
            new_name='vaccination_date',
        ),
    ]
