# Generated by Django 3.0.5 on 2020-04-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_website', '0017_auto_20200422_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination',
            name='vaccination_type',
            field=models.CharField(default='----', max_length=50),
        ),
    ]
