# Generated by Django 3.0.5 on 2020-04-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_website', '0018_auto_20200422_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='milk_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_no', models.CharField(max_length=20)),
                ('milk_quantity', models.IntegerField()),
                ('milk_date', models.DateField()),
                ('milk_time', models.CharField(max_length=20)),
                ('farmer_id', models.CharField(max_length=20)),
            ],
        ),
    ]
