# Generated by Django 3.0.5 on 2020-04-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_website', '0021_auto_20200426_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination',
            name='farmer_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
