# Generated by Django 3.0.5 on 2020-04-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_website', '0022_vaccination_farmer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='deworming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_no', models.CharField(default='no selected', max_length=34)),
                ('deworming_date', models.CharField(default='----', max_length=50)),
                ('medicine_name', models.DateField(default='----')),
                ('due_date', models.DateField(default='2020-02-02')),
                ('farmer_id', models.CharField(max_length=20)),
            ],
        ),
    ]
