# Generated by Django 3.0.5 on 2020-04-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_website', '0023_deworming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deworming',
            name='medicine_name',
            field=models.CharField(default='----', max_length=200),
        ),
    ]
