# Generated by Django 3.0.5 on 2020-05-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_website', '0024_auto_20200426_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('que_id', models.IntegerField(primary_key=True, serialize=False)),
                ('farmer_id_que', models.IntegerField()),
                ('que_subject', models.CharField(max_length=200)),
                ('que_body', models.CharField(max_length=500)),
                ('que_date', models.DateField()),
            ],
        ),
    ]
