# Generated by Django 3.0.5 on 2020-05-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_website', '0027_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='que_id',
            field=models.CharField(max_length=100),
        ),
    ]
