# Generated by Django 3.0.5 on 2020-05-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_website', '0029_auto_20200512_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal_record',
            name='animal_type_age',
            field=models.CharField(default='calf', max_length=20),
        ),
    ]
