# Generated by Django 3.0.5 on 2020-05-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_website', '0030_animal_record_animal_type_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deworming',
            name='deworming_date',
            field=models.DateField(default='2020-02-02'),
        ),
    ]
