# Generated by Django 3.0.5 on 2020-06-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_website', '0031_auto_20200520_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='dislikes',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='questions',
            name='likes',
            field=models.IntegerField(default=20),
        ),
    ]
