# Generated by Django 3.0.5 on 2020-06-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_website', '0033_auto_20200617_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal_record',
            name='farmer_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='farmer_id',
            field=models.IntegerField(),
        ),
    ]
