# Generated by Django 3.0.5 on 2020-06-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_website', '0034_auto_20200617_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deworming',
            name='farmer_id',
            field=models.IntegerField(),
        ),
    ]
