# Generated by Django 3.0.5 on 2020-06-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_website', '0036_auto_20200617_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questions',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
